---
all:
  children:
    linux_servers:
      children:
        webservers:
          hosts:
            qa-web-01:

        appservers:
          hosts:
            qa-app-01:

        monitoring:
          hosts:
            qa-mon-01: